# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e92988b310c49e5e04dc9be71e76da97c51a5937407dfb935d3cd65d963a761ec3fbaa232e0d93eb5b6daf73342794f7dad74e9cb0f198c88648b147762ff40d

test:
  secret_key_base: 4fe99dc3026a08f4975dc220cb67e6bcff4b19a310900aeeb7727a4a1f5e6b7acba7922379dfc7eb832922a45e28d5dd5d5b01673560a747505a53c4c35661b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
